name: bladderreport
channels:
  - dranew
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
    -  r-base
    - r-base-dev
    - libblas3
    - libblas-dev
    - liblapack-dev
    - liblapack3
    -  r-utf8
    -  r-ranger
    -  r-devtools
    -  r-knitr
    -  r-kableextra
    -  r-jsonlite
    -  r-dplyr
    -  r-reshape
    -  r-ggplot2
    -  r-cowplot=1.1.0
    -  r-gridextra
